package models;
// Generated Nov 23, 2021 7:39:07 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ChatMessage generated by hbm2java
 */
public class ChatMessage  implements java.io.Serializable {


     private Integer id;
     private User userByUserSenderId;
     private User userByUserReceiverId;
     private UserToken userToken;
     private String uuid;
     private int status;
     private String text;
     private Date updatedAt;
     private Date createdAt;
     private Date deletedAt;
     private Set userNotifications = new HashSet(0);

    public ChatMessage() {
    }

	
    public ChatMessage(User userByUserSenderId, User userByUserReceiverId, UserToken userToken, String uuid, int status, String text) {
        this.userByUserSenderId = userByUserSenderId;
        this.userByUserReceiverId = userByUserReceiverId;
        this.userToken = userToken;
        this.uuid = uuid;
        this.status = status;
        this.text = text;
    }
    public ChatMessage(User userByUserSenderId, User userByUserReceiverId, UserToken userToken, String uuid, int status, String text, Date updatedAt, Date createdAt, Date deletedAt, Set userNotifications) {
       this.userByUserSenderId = userByUserSenderId;
       this.userByUserReceiverId = userByUserReceiverId;
       this.userToken = userToken;
       this.uuid = uuid;
       this.status = status;
       this.text = text;
       this.updatedAt = updatedAt;
       this.createdAt = createdAt;
       this.deletedAt = deletedAt;
       this.userNotifications = userNotifications;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUserByUserSenderId() {
        return this.userByUserSenderId;
    }
    
    public void setUserByUserSenderId(User userByUserSenderId) {
        this.userByUserSenderId = userByUserSenderId;
    }
    public User getUserByUserReceiverId() {
        return this.userByUserReceiverId;
    }
    
    public void setUserByUserReceiverId(User userByUserReceiverId) {
        this.userByUserReceiverId = userByUserReceiverId;
    }
    public UserToken getUserToken() {
        return this.userToken;
    }
    
    public void setUserToken(UserToken userToken) {
        this.userToken = userToken;
    }
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getDeletedAt() {
        return this.deletedAt;
    }
    
    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }
    public Set getUserNotifications() {
        return this.userNotifications;
    }
    
    public void setUserNotifications(Set userNotifications) {
        this.userNotifications = userNotifications;
    }




}


