package models;
// Generated Nov 23, 2021 7:39:07 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PostAttachment generated by hbm2java
 */
public class PostAttachment  implements java.io.Serializable {


     private Integer id;
     private Post post;
     private User user;
     private UserToken userToken;
     private int attachmentType;
     private String filename;
     private String filepath;
     private int filesize;
     private Date updatedAt;
     private Date createdAt;
     private Date deletedAt;

    public PostAttachment() {
    }

	
    public PostAttachment(Post post, User user, UserToken userToken, int attachmentType, String filename, String filepath, int filesize) {
        this.post = post;
        this.user = user;
        this.userToken = userToken;
        this.attachmentType = attachmentType;
        this.filename = filename;
        this.filepath = filepath;
        this.filesize = filesize;
    }
    public PostAttachment(Post post, User user, UserToken userToken, int attachmentType, String filename, String filepath, int filesize, Date updatedAt, Date createdAt, Date deletedAt) {
       this.post = post;
       this.user = user;
       this.userToken = userToken;
       this.attachmentType = attachmentType;
       this.filename = filename;
       this.filepath = filepath;
       this.filesize = filesize;
       this.updatedAt = updatedAt;
       this.createdAt = createdAt;
       this.deletedAt = deletedAt;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Post getPost() {
        return this.post;
    }
    
    public void setPost(Post post) {
        this.post = post;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public UserToken getUserToken() {
        return this.userToken;
    }
    
    public void setUserToken(UserToken userToken) {
        this.userToken = userToken;
    }
    public int getAttachmentType() {
        return this.attachmentType;
    }
    
    public void setAttachmentType(int attachmentType) {
        this.attachmentType = attachmentType;
    }
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }
    public String getFilepath() {
        return this.filepath;
    }
    
    public void setFilepath(String filepath) {
        this.filepath = filepath;
    }
    public int getFilesize() {
        return this.filesize;
    }
    
    public void setFilesize(int filesize) {
        this.filesize = filesize;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getDeletedAt() {
        return this.deletedAt;
    }
    
    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }




}


