package models;
// Generated Nov 23, 2021 7:39:07 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PostAttachment generated by hbm2java
 */
public class PostAttachment extends Model<PostAttachment> implements java.io.Serializable  {


     private Post post;
     private User user;
     private UserToken userToken;
     private int attachmentType;
     private String filename;
     private String filepath;
     private int filesize;

    public PostAttachment() {
        this._table_name = "PostAttachment";
    }

	
    public PostAttachment(Post post, User user, UserToken userToken, int attachmentType, String filename, String filepath, int filesize) {
        this();
        this.post = post;
        this.user = user;
        this.userToken = userToken;
        this.attachmentType = attachmentType;
        this.filename = filename;
        this.filepath = filepath;
        this.filesize = filesize;
    }
    public PostAttachment(Post post, User user, UserToken userToken, int attachmentType, String filename, String filepath, int filesize, Date updatedAt, Date createdAt, Date deletedAt) {
       this();
       this.post = post;
       this.user = user;
       this.userToken = userToken;
       this.attachmentType = attachmentType;
       this.filename = filename;
       this.filepath = filepath;
       this.filesize = filesize;
       this.updatedAt = updatedAt;
       this.createdAt = createdAt;
       this.deletedAt = deletedAt;
    }
   
    public Post getPost() {
        return this.post;
    }
    
    public void setPost(Post post) {
        this.post = post;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public UserToken getUserToken() {
        return this.userToken;
    }
    
    public void setUserToken(UserToken userToken) {
        this.userToken = userToken;
    }
    public int getAttachmentType() {
        return this.attachmentType;
    }
    
    public void setAttachmentType(int attachmentType) {
        this.attachmentType = attachmentType;
    }
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }
    public String getFilepath() {
        return this.filepath;
    }
    
    public void setFilepath(String filepath) {
        this.filepath = filepath;
    }
    public int getFilesize() {
        return this.filesize;
    }
    
    public void setFilesize(int filesize) {
        this.filesize = filesize;
    }
    
}


