package models;
// Generated Nov 23, 2021 7:39:07 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Post generated by hbm2java
 */
public class Post  implements java.io.Serializable {


     private Integer id;
     private User user;
     private UserToken userToken;
     private String uuid;
     private String text;
     private Date updatedAt;
     private Date createdAt;
     private Date deletedAt;
     private Set postHashtags = new HashSet(0);
     private Set postUserTags = new HashSet(0);
     private Set postComments = new HashSet(0);
     private Set postAttachments = new HashSet(0);
     private Set postReactions = new HashSet(0);

    public Post() {
    }

	
    public Post(User user, UserToken userToken, String uuid, String text) {
        this.user = user;
        this.userToken = userToken;
        this.uuid = uuid;
        this.text = text;
    }
    public Post(User user, UserToken userToken, String uuid, String text, Date updatedAt, Date createdAt, Date deletedAt, Set postHashtags, Set postUserTags, Set postComments, Set postAttachments, Set postReactions) {
       this.user = user;
       this.userToken = userToken;
       this.uuid = uuid;
       this.text = text;
       this.updatedAt = updatedAt;
       this.createdAt = createdAt;
       this.deletedAt = deletedAt;
       this.postHashtags = postHashtags;
       this.postUserTags = postUserTags;
       this.postComments = postComments;
       this.postAttachments = postAttachments;
       this.postReactions = postReactions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public UserToken getUserToken() {
        return this.userToken;
    }
    
    public void setUserToken(UserToken userToken) {
        this.userToken = userToken;
    }
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getDeletedAt() {
        return this.deletedAt;
    }
    
    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }
    public Set getPostHashtags() {
        return this.postHashtags;
    }
    
    public void setPostHashtags(Set postHashtags) {
        this.postHashtags = postHashtags;
    }
    public Set getPostUserTags() {
        return this.postUserTags;
    }
    
    public void setPostUserTags(Set postUserTags) {
        this.postUserTags = postUserTags;
    }
    public Set getPostComments() {
        return this.postComments;
    }
    
    public void setPostComments(Set postComments) {
        this.postComments = postComments;
    }
    public Set getPostAttachments() {
        return this.postAttachments;
    }
    
    public void setPostAttachments(Set postAttachments) {
        this.postAttachments = postAttachments;
    }
    public Set getPostReactions() {
        return this.postReactions;
    }
    
    public void setPostReactions(Set postReactions) {
        this.postReactions = postReactions;
    }




}


