package models;
// Generated Nov 23, 2021 7:39:07 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User extends Model<User> implements java.io.Serializable {

    
    private String name;
    private String lastName;
    private String email;
    private String phone;
    private String passwd;
    private Date bornDate;
    private String gender;
    private String profilePicturePath;
    private Set userNotifications = new HashSet(0);
    private Set postAttachments = new HashSet(0);
    private Set postReactions = new HashSet(0);
    private Set chatMessagesForUserSenderId = new HashSet(0);
    private Set postUserTagsForUserId = new HashSet(0);
    private Set postUserTagsForUserTagId = new HashSet(0);
    private Set chatMessagesForUserReceiverId = new HashSet(0);
    private Set postComments = new HashSet(0);
    private Set userTokens = new HashSet(0);
    private Set posts = new HashSet(0);
    private Set postHashtags = new HashSet(0);

    public User() {
        this._table_name = "User";
    }

    public User(String name, String lastName, String email, String phone, String passwd, Date bornDate, String gender) {
        this();
        this.name = name;
        this.lastName = lastName;
        this.email = email;
        this.phone = phone;
        this.passwd = passwd;
        this.bornDate = bornDate;
        this.gender = gender;        
    }

    public User(String name, String lastName, String email, String phone, String passwd, Date bornDate, String gender, Date updatedAt, Date createdAt, Date deletedAt, Set userNotifications, Set postAttachments, Set postReactions, Set chatMessagesForUserSenderId, Set postUserTagsForUserId, Set postUserTagsForUserTagId, Set chatMessagesForUserReceiverId, Set postComments, Set userTokens, Set posts, Set postHashtags) {
        this();
        this.name = name;
        this.lastName = lastName;
        this.email = email;
        this.phone = phone;
        this.passwd = passwd;
        this.bornDate = bornDate;
        this.gender = gender;
        this.updatedAt = updatedAt;
        this.createdAt = createdAt;
        this.deletedAt = deletedAt;
        this.userNotifications = userNotifications;
        this.postAttachments = postAttachments;
        this.postReactions = postReactions;
        this.chatMessagesForUserSenderId = chatMessagesForUserSenderId;
        this.postUserTagsForUserId = postUserTagsForUserId;
        this.postUserTagsForUserTagId = postUserTagsForUserTagId;
        this.chatMessagesForUserReceiverId = chatMessagesForUserReceiverId;
        this.postComments = postComments;
        this.userTokens = userTokens;
        this.posts = posts;
        this.postHashtags = postHashtags;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getPasswd() {
        return this.passwd;
    }

    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

    public Date getBornDate() {
        return this.bornDate;
    }

    public void setBornDate(Date bornDate) {
        this.bornDate = bornDate;
    }

    public String getGender() {
        return this.gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public Set getUserNotifications() {
        return this.userNotifications;
    }

    public void setUserNotifications(Set userNotifications) {
        this.userNotifications = userNotifications;
    }

    public Set getPostAttachments() {
        return this.postAttachments;
    }

    public void setPostAttachments(Set postAttachments) {
        this.postAttachments = postAttachments;
    }

    public Set getPostReactions() {
        return this.postReactions;
    }

    public void setPostReactions(Set postReactions) {
        this.postReactions = postReactions;
    }

    public Set getChatMessagesForUserSenderId() {
        return this.chatMessagesForUserSenderId;
    }

    public void setChatMessagesForUserSenderId(Set chatMessagesForUserSenderId) {
        this.chatMessagesForUserSenderId = chatMessagesForUserSenderId;
    }

    public Set getPostUserTagsForUserId() {
        return this.postUserTagsForUserId;
    }

    public void setPostUserTagsForUserId(Set postUserTagsForUserId) {
        this.postUserTagsForUserId = postUserTagsForUserId;
    }

    public Set getPostUserTagsForUserTagId() {
        return this.postUserTagsForUserTagId;
    }

    public void setPostUserTagsForUserTagId(Set postUserTagsForUserTagId) {
        this.postUserTagsForUserTagId = postUserTagsForUserTagId;
    }

    public Set getChatMessagesForUserReceiverId() {
        return this.chatMessagesForUserReceiverId;
    }

    public void setChatMessagesForUserReceiverId(Set chatMessagesForUserReceiverId) {
        this.chatMessagesForUserReceiverId = chatMessagesForUserReceiverId;
    }

    public Set getPostComments() {
        return this.postComments;
    }

    public void setPostComments(Set postComments) {
        this.postComments = postComments;
    }

    public Set getUserTokens() {
        return this.userTokens;
    }

    public void setUserTokens(Set userTokens) {
        this.userTokens = userTokens;
    }

    public Set getPosts() {
        return this.posts;
    }

    public void setPosts(Set posts) {
        this.posts = posts;
    }

    public Set getPostHashtags() {
        return this.postHashtags;
    }

    public void setPostHashtags(Set postHashtags) {
        this.postHashtags = postHashtags;
    }

    public String getProfilePicturePath() {
        return profilePicturePath;
    }

    public void setProfilePicturePath(String profilePicturePath) {
        this.profilePicturePath = profilePicturePath;
    }

    
}
