package models;
// Generated Nov 23, 2021 7:39:07 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * UserNotification generated by hbm2java
 */
public class UserNotification  implements java.io.Serializable {


     private Integer id;
     private ChatMessage chatMessage;
     private PostComment postComment;
     private PostReaction postReaction;
     private User user;
     private int notificationType;
     private boolean isSeen;
     private Date updatedAt;
     private Date createdAt;
     private Date deletedAt;

    public UserNotification() {
    }

	
    public UserNotification(ChatMessage chatMessage, PostComment postComment, PostReaction postReaction, User user, int notificationType, boolean isSeen) {
        this.chatMessage = chatMessage;
        this.postComment = postComment;
        this.postReaction = postReaction;
        this.user = user;
        this.notificationType = notificationType;
        this.isSeen = isSeen;
    }
    public UserNotification(ChatMessage chatMessage, PostComment postComment, PostReaction postReaction, User user, int notificationType, boolean isSeen, Date updatedAt, Date createdAt, Date deletedAt) {
       this.chatMessage = chatMessage;
       this.postComment = postComment;
       this.postReaction = postReaction;
       this.user = user;
       this.notificationType = notificationType;
       this.isSeen = isSeen;
       this.updatedAt = updatedAt;
       this.createdAt = createdAt;
       this.deletedAt = deletedAt;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public ChatMessage getChatMessage() {
        return this.chatMessage;
    }
    
    public void setChatMessage(ChatMessage chatMessage) {
        this.chatMessage = chatMessage;
    }
    public PostComment getPostComment() {
        return this.postComment;
    }
    
    public void setPostComment(PostComment postComment) {
        this.postComment = postComment;
    }
    public PostReaction getPostReaction() {
        return this.postReaction;
    }
    
    public void setPostReaction(PostReaction postReaction) {
        this.postReaction = postReaction;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public int getNotificationType() {
        return this.notificationType;
    }
    
    public void setNotificationType(int notificationType) {
        this.notificationType = notificationType;
    }
    public boolean isIsSeen() {
        return this.isSeen;
    }
    
    public void setIsSeen(boolean isSeen) {
        this.isSeen = isSeen;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getDeletedAt() {
        return this.deletedAt;
    }
    
    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }




}


