package models;
// Generated Nov 23, 2021 7:39:07 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UserToken generated by hbm2java
 */
public class UserToken extends Model<UserToken> implements java.io.Serializable {

    private User user;
    private String ipAddress;
    private String uuid;
    private Date vigency;
    private Set postComments = new HashSet(0);
    private Set postReactions = new HashSet(0);
    private Set postUserTags = new HashSet(0);
    private Set postHashtags = new HashSet(0);
    private Set posts = new HashSet(0);
    private Set chatMessages = new HashSet(0);
    private Set postAttachments = new HashSet(0);

    public UserToken() {
        this._table_name = "UserToken";
    }

    public UserToken(User user, String ipAddress, String uuid, Date vigency) {
        this();
        this.user = user;
        this.ipAddress = ipAddress;
        this.uuid = uuid;
        this.vigency = vigency;
    }

    public UserToken(User user, String ipAddress, String uuid, Date vigency, Date updatedAt, Date createdAt, Date deletedAt, Set postComments, Set postReactions, Set postUserTags, Set postHashtags, Set posts, Set chatMessages, Set postAttachments) {
        this();
        this.user = user;
        this.ipAddress = ipAddress;
        this.uuid = uuid;
        this.vigency = vigency;
        this.updatedAt = updatedAt;
        this.createdAt = createdAt;
        this.deletedAt = deletedAt;
        this.postComments = postComments;
        this.postReactions = postReactions;
        this.postUserTags = postUserTags;
        this.postHashtags = postHashtags;
        this.posts = posts;
        this.chatMessages = chatMessages;
        this.postAttachments = postAttachments;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public String getIpAddress() {
        return this.ipAddress;
    }

    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    public String getUuid() {
        return this.uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public Date getVigency() {
        return this.vigency;
    }

    public void setVigency(Date vigency) {
        this.vigency = vigency;
    }

    public Set getPostComments() {
        return this.postComments;
    }

    public void setPostComments(Set postComments) {
        this.postComments = postComments;
    }

    public Set getPostReactions() {
        return this.postReactions;
    }

    public void setPostReactions(Set postReactions) {
        this.postReactions = postReactions;
    }

    public Set getPostUserTags() {
        return this.postUserTags;
    }

    public void setPostUserTags(Set postUserTags) {
        this.postUserTags = postUserTags;
    }

    public Set getPostHashtags() {
        return this.postHashtags;
    }

    public void setPostHashtags(Set postHashtags) {
        this.postHashtags = postHashtags;
    }

    public Set getPosts() {
        return this.posts;
    }

    public void setPosts(Set posts) {
        this.posts = posts;
    }

    public Set getChatMessages() {
        return this.chatMessages;
    }

    public void setChatMessages(Set chatMessages) {
        this.chatMessages = chatMessages;
    }

    public Set getPostAttachments() {
        return this.postAttachments;
    }

    public void setPostAttachments(Set postAttachments) {
        this.postAttachments = postAttachments;
    }

}
